---
version: '3'

includes:
  format: ./taskfiles/Taskfile.format.yml
  lint: ./taskfiles/Taskfile.lint.yml
  references: ./taskfiles/Taskfile.references.yml
  snippets: ./taskfiles/Taskfile.snippets.yml
  site: ./taskfiles/Taskfile.site.yml

tasks:
  setup:
    desc: Install Python and Node dependencies
    cmds:
      - mise install
      - uv sync
      - pnpm install --frozen-lockfile

  update:
    desc: Update and install Python and Node dependencies
    cmds:
      - mise install
      - uv sync --upgrade
      - pnpm install

  dev:
    desc: Start dev server
    vars:
      HOST: '{{.HOST | default ""}}'
      PORT: '{{.PORT | default ""}}'
    cmds:
      - task: site:dev
        vars:
          HOST: '{{.HOST}}'
          PORT: '{{.PORT}}'

  build:
    desc: Build site
    cmds:
      - task: site:build

  preview:
    desc: Preview built site
    vars:
      HOST: '{{.HOST | default ""}}'
      PORT: '{{.PORT | default ""}}'
    cmds:
      - task: site:preview
        vars:
          HOST: '{{.HOST}}'
          PORT: '{{.PORT}}'

  format:
    cmds:
      - task: format:all

  lint:
    cmds:
      - task: lint:all
